### ISSUE TITLE
Replace the Logo of Layer5 with Service-Mesh-Patterns in config.yml workflow

### ISSUE THREAD

**Issue by anshgoyalevil** [service-mesh-patterns/service-mesh-patterns#102]
### Description

Currently, we are using the Logo of Layer5 instead of service-mesh-patterns. This repository is under the organization service-mesh-patterns, so, there should be the image of service-mesh-patterns.

**How to resolve this?**
- Go to .github and replace this welcome image with the new one: 

![Service-Mesh-Patterns-celebration](https://user-images.githubusercontent.com/94157520/231491424-6243453c-17d9-4132-921e-863384b2f4e0.png)

- Download this image, and upload with the correct name for future reference. The name of the image should be Service-Mesh-Patterns-celebration
- After uploading the image, and removing the previous image, go to .github/config.yml folder and update the reference to previous image to the new image in the following part:

```
firstPRMergeComment: >
  Thanks for your contribution to the Layer5 and Meshery community! :tada:
   
  ![Congrats!](https://raw.githubusercontent.com/meshery/meshery.io/master/.github/welcome/Layer5-celebration.png)
  &nbsp; &#9; &nbsp; &#9;  &nbsp; &#9;  &nbsp; &#9; :star: Please leave a [star on the project](../stargazers). :smile:
```
- That's it.

-----
#### Contributor Guides and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing](https://github.com/service-mesh-patterns/service-mesh-patterns/blob/master/CONTRIBUTING.md)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by senali-d** [comment]
I would like to work on this issue.
