### ISSUE TITLE
Issue Template Updates for Figma link 

### ISSUE THREAD

**Issue by thisiskaransgit** [service-mesh-patterns/service-mesh-patterns#112]
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should have an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

**Acceptance Tests**
All references to Figma include the "open invite" link.

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by Harsh-2004** [comment]
Can I work on this pls

**Comment by Harsh-2004** [comment]
@thisiskaransgit

**Comment by Apoorvyash** [comment]
hi, @thisiskaransgit @leecalcote 
I have deep experience in figma and UI building, of mobile as well as web applications, Can you please assign me this issue?

**Comment by Ghat0tkach** [comment]
We assign issues on the first-come first serve basis @Apoorvyash  , there are a lot of similar issues available you can check [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22)

Meanwhile @Harsh-2004  , you can start working on this issue . Karan will assign you soon . 
Remember NO PR without assignment of issue.

**Comment by Apoorvyash** [comment]
@Ghat0tkach @leecalcote absolutely, that's a neat practice, so can you please assign me this issue then?https://github.com/layer5io/helm-chart-releaser/issues/12

**Comment by nakulbh** [comment]
Hey @leecalcote @thisiskaransgit  is this issue still open 
can i work on it

**Comment by nakulbh** [comment]
Hey @leecalcote @thisiskaransgit Theres only one refrence to Figma in ISSUE TEMPLATES. I have Updated it. I want to make a PR. Should i make it ?

**Comment by Karmpatel960** [comment]
Hey @leecalcote Can you please assign me this if it is not completed?

**Comment by thisiskaransgit** [comment]
@Harsh-2004, are you still actively working on the issue? Please signal if you're not, so we can reassign it to other contributor

**Comment by Harsh-2004** [comment]
Pls reassign I had an accident and was disconnected sry

**Comment by thisiskaransgit** [comment]
@Karmpatel960, go ahead with this one 💪🏼

**Comment by Ghat0tkach** [comment]
> Pls reassign I had an accident and was disconnected sry

Is Everything okay now?

**Comment by nakulbh** [comment]
I Think this issue is fixed I raised a PR for it a 3 days ago. @leecalcote Sir please close this issue

**Comment by leecalcote** [comment]
@nakulbh reach out to the individual that opened this issue or you'll unfortunately likely be waiting another 3 days before I can respond.

**Comment by thisiskaransgit** [comment]
Hey @nakulbh, We kindly request that contributors refrain from submitting direct pull requests without prior assignment. Our approach is to assign issues based on chronological order, ensuring fairness in distribution among contributors. If the initial assignee fails to address or resolve the issue, we then move on to the next contributor in line.
Please understand that while exceptions may [exist](https://layer5.io/community/handbook/faq), this process allows us to manage contributions effectively and ensure equal opportunities for all interested individuals. 

 In this case, the PR that got merged did not incorporate all the required changes, moreover, there was a formatting change, which needed to be fixed.
 
 Please take care of these things in the near future.
