### ISSUE TITLE
Inconsistency in footer layout compare to other page footer layout on layer5

### ISSUE THREAD

**Issue by Cvr421** [service-mesh-patterns/service-mesh-patterns#113]
#### Description

On service-mesh-pattern website the footer layout is not consistent with other pages footer layout on layer5.
https://service-mesh-patterns.github.io/service-mesh-patterns/

Behavior
![Screenshot 2023-07-19 201855](https://github.com/service-mesh-patterns/service-mesh-patterns/assets/82499697/5d2df936-e655-4034-b202-fa77e3b2c949)

#### Expected Behavior

![Screenshot 2023-07-19 201930](https://github.com/service-mesh-patterns/service-mesh-patterns/assets/82499697/474a8cd4-fb8d-4892-9901-8385d99437e5)

#### Environment:
- Meshery Version: 
- Kubernetes Version: 
- Host OS:
- Browser:

**Comment by Chadha93** [comment]
Assigned @Cvr421. All yours. Please also address this in this issue - https://layer5io.slack.com/archives/C015QJKUMPU/p1689864226229019?thread_ts=1689781477.372719&cid=C015QJKUMPU

**Comment by Cvr421** [comment]
> Assigned @Cvr421. All yours. Please also address this in this issue - https://layer5io.slack.com/archives/C015QJKUMPU/p1689864226229019?thread_ts=1689781477.372719&cid=C015QJKUMPU
ok thanks @Chadha93

**Comment by nakulbh** [comment]
Hey @Chadha93 can i Work on this issue

**Comment by leecalcote** [comment]
Please see - https://github.com/service-mesh-patterns/service-mesh-patterns/pull/114#issuecomment-1646624448
