### ISSUE TITLE
[Docs] Add Service Mesh Patterns logo with text to README

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-patterns/service-mesh-patterns#12]
**Current State:**
This repo's readme includes the patterns logo w/o text (without the word PATTERNS).

**Desired State:**
Replace the existing logo with this one that has text included.

[service-mesh-patterns-side.svg.zip](https://github.com/service-mesh-patterns/service-mesh-patterns/files/7375487/service-mesh-patterns-side.svg.zip)

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by IamEzio** [comment]
@leecalcote, Can i work on this issue?

**Comment by Chadha93** [comment]
@IamEzio Thanks for engaging, feel free to pick issues. :)
Closing issue,  already fixed.
