### ISSUE TITLE
Remove "above" from label-commenter-config.yml

### ISSUE THREAD

**Issue by vishalvivekm** [service-mesh-patterns/service-mesh-patterns#120]
Remove `above` from "DCO check above" on line 26 and 31
https://github.com/service-mesh-patterns/service-mesh-patterns/blob/cebc315b33d1d82ea8d0093160e0e0a8f1995df7/.github/label-commenter-config.yml#L26
line 31 https://github.com/service-mesh-patterns/service-mesh-patterns/blob/cebc315b33d1d82ea8d0093160e0e0a8f1995df7/.github/label-commenter-config.yml#L31

**Comment by Mohiit70** [comment]
can you assign me this issue

**Comment by abhijeetgauravm** [comment]
i can work on this issue!

**Comment by sudhanshutech** [comment]
assigning in fcfs order // @Chadha93

**Comment by Mohiit70** [comment]
> assigning in fcfs order // @Chadha93

I have made this pull request. Kindly review and provide feedback. Thank you!
