### ISSUE TITLE
Change Twitter Logo to Xi(New logo)

### ISSUE THREAD

**Issue by EraKin575** [service-mesh-patterns/service-mesh-patterns#121]
**Current State of the Service Mesh Patterns site**
Old logo is present on the website
![image](https://github.com/service-mesh-patterns/service-mesh-patterns/assets/100225222/3a26ff6a-d965-4c7a-95b4-f566605fc39e)

**Desired State of the Service Mesh Patterns site**
Change twitter logo to X
![image](https://github.com/service-mesh-patterns/service-mesh-patterns/assets/100225222/96a2a17f-a7d8-43de-9217-8f332281678b)

---
### Contributor Resources
This website uses React and GitHub Pages. Site content is found under the [`master` branch](https://github.com/service-mesh-books/service-mesh-patterns/tree/master/src).
- See the [Contributing to Service Mesh Patterns Website](https://github.com/service-mesh-patterns/service-mesh-patterns/#readme) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- Layer5 [Brand Kit](https://layer5.io/company/brand)
- 📑 [Service Mesh Patterns in Meshery Catalog](https://meshery.io/catalog)
- 📖 [Service Mesh Patterns Book](https://layer5.io/learn/service-mesh-books/service-mesh-patterns)
- - 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Karmpatel960 please ask other maintainers / contributors so that I don't slow you down. @thisiskaransgit
