### ISSUE TITLE
Add service-mesh-patterns to Templates category on ReposHub

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-patterns/service-mesh-patterns#16]
**Current Behavior**
ReposHub has a section for Templates: https://reposhub.com/tags/templates

**Desired Behavior**
Contact ReposHub to have this repo added to the Templates category.

**Comment by leecalcote** [comment]
Success?

**Comment by Chadha93** [comment]
@sayantan1413 on it?

**Comment by sayantan1413** [comment]
Hey, @Chadha93 and @leecalcote no I didn't receive any reply from repo hub, and also the GitHub link in their main website is broken. (https://github.com/reposhub). So I didn't find any option for how to add it.

**Comment by leecalcote** [comment]
ok, thank you for trying, @sayantan1413 . I suppose its appropriate to close this issue given your findings. ✔️
