### ISSUE TITLE
Design website for Service Mesh Patterns

### ISSUE THREAD

**Issue by debo19** [service-mesh-patterns/service-mesh-patterns#33]
#### Current Behavior
We don't have a website hosted on this repository for service mesh patterns.

#### Desired Behavior
Design a simple, one page site dedicated to the [service mesh patterns book](https://layer5.io/learn/service-mesh-books/service-mesh-patterns).

#### Resources

-  Layer5 [Brand Kit](https://layer5.io/company/brand)
-  [Service Mesh Patterns Book](https://layer5.io/learn/service-mesh-books/service-mesh-patterns)
-  Layer5 [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5310%3A0) 

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by suvrashaw** [comment]
@debo19 @leecalcote Would love to work on this.

**Comment by debo19** [comment]
Sure @suvrashaw, go ahead

**Comment by alexisdsgns** [comment]
@debo19 @leecalcote @suvrashaw I would love to assist you on this, please.

**Comment by debo19** [comment]
Sure @alexisdsgns. Ivarr is working on the home page for now. I've shared a couple of instructions with him. You can collaborate with him or take up any of the remaining pages. Please reach out on slack, preferably on #websites channel so that all of us are in the loop.

**Comment by alexisdsgns** [comment]
I and Ívarr Winter have commenced working on the tasks provided, we should have something on/before Wednesday. We would update you in the #websites channel and definitely keep you in the loop.
