### ISSUE TITLE
[Epic][Site] Implement Main Page

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-patterns/service-mesh-patterns#38]
#### Current Behavior
No main page has been implemented (based on the completed mockup) for the Service Mesh Patterns book website.
Main Page Design: [Figma Link](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=8621%3A14101)

#### Desired Behavior
Design a simple, one-page site dedicated to the [service mesh patterns book](https://layer5.io/learn/service-mesh-books/service-mesh-patterns).

- [x] #52 
- [x] #53 
- [x] #54 
- [x] #55 

---
#### Resources
- Layer5 [Brand Kit](https://layer5.io/company/brand)
- [Service Mesh Patterns Book](https://layer5.io/learn/service-mesh-books/service-mesh-patterns)
- [Designs in Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5310%3A0) 
- [Service Mesh Patterns in Meshery Catalog](https://meshery.io/catalog)

**Comment by Palaksharma23** [comment]
I would love to work on this issue, Can I take this up @leecalcote @Nikhil-Ladha  :)

**Comment by Nikhil-Ladha** [comment]
You can start off with the Navbar of the page.
And, once that's done another section could be picked up.

**Comment by Nikhil-Ladha** [comment]
Follow the code structure of layer5 repo.
I have added an empty folder under `src/sections` named `NavBar`, Please update the code there, and follow the structuring similar to the layer repo.

**Comment by bhavyastar** [comment]
I would love to work on this issue, Can I start working on this? @leecalcote @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Sure, @bhavyastar you can take up the hero section of the page.
Follow the structuring as mentioned above.

**Comment by Nikhil-Ladha** [comment]
I have updated the design link in the issue description for feasibility :)

**Comment by legendarykamal** [comment]
@Nikhil-Ladha should i work on footer component? as i see its been approved too :)

**Comment by Nikhil-Ladha** [comment]
If @bhavyastar , @Palaksharma23 @legendarykamal you all are inclined in working towards the sections then please comment on the issues for assignment respectively. Clearing all the assignments from this issue for now.

**Comment by Palaksharma23** [comment]
sure @Nikhil-Ladha :)
