### ISSUE TITLE
[Site] Add the author section

### ISSUE THREAD

**Issue by bhavyastar** [service-mesh-patterns/service-mesh-patterns#63]
**Current State of the Service Mesh Patterns site**

An author section needs to be added as per Figma design! 

**Desired State of the Service Mesh Patterns site**

---
### Contributor Resources
This website uses React and GitHub Pages. Site content is found under the [`master` branch](https://github.com/service-mesh-books/service-mesh-patterns/tree/master/src).
- See the [Contributing to Service Mesh Patterns Website](https://github.com/service-mesh-patterns/service-mesh-patterns/#readme) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- Layer5 [Brand Kit](https://layer5.io/company/brand)
- 📑 [Service Mesh Patterns in Meshery Catalog](https://meshery.io/catalog)
- 📖 [Service Mesh Patterns Book](https://layer5.io/learn/service-mesh-books/service-mesh-patterns)
- 🎨 [Site designs in Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5310%3A0). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Nikhil-Ladha** [comment]
Assigned the issue to you, @bhavyastar .
Though, can you please share the design link that you are planning to implement in this issue?

**Comment by bhavyastar** [comment]
https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=8847%3A14997
I am referring this design!

**Comment by Nikhil-Ladha** [comment]
So, are you implementing the complete page?
I see Kamal's name being assigned next to it 🤔

**Comment by bhavyastar** [comment]
I am in the middle of this. I can make a draft PR for this!

**Comment by bhavyastar** [comment]
I am implementing the author's section!
