### ISSUE TITLE
[Site] Add the github hosted link to the repo

### ISSUE THREAD

**Issue by legendarykamal** [service-mesh-patterns/service-mesh-patterns#75]
**Current State:**
Since the main page has been completed now, we can add the github hosted link to the github repo .

**Desired State:**

Adding the hosted link  https://service-mesh-patterns.github.io/service-mesh-patterns/ 

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
https://service-mesh-patterns.github.io/service-mesh-patterns website link added to the repo's About section. ✔️

**Comment by legendarykamal** [comment]
Thank you @leecalcote for taking heads up :)
