### ISSUE TITLE
[Docs] Add deployment instructions for patterns

### ISSUE THREAD

**Issue by Chadha93** [service-mesh-patterns/service-mesh-patterns#8]
**Current State:**
The readme does not have any information about the deployment of patterns

**Desired State:**
Add a section about(Actions in Patterns UI) deployment for patterns. 

**Reference Docs**
https://docs.meshery.io/functionality/pattern-management

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by navendu-pottekkat** [comment]
@l5io Testing...

**Comment by leecalcote** [comment]
@ piyushsingariya...

**Comment by leecalcote** [comment]
@Chadha93 you can add a link to the `mesheryctl` reference guide so that a contributor can pick this up more easily.

**Comment by Deepansharora27** [comment]
I would like to take this up @leecalcote

**Comment by Chadha93** [comment]
> 

Sure, updating it in the issue description

**Comment by Chadha93** [comment]
> @Chadha93 you can add a link to the `mesheryctl` reference guide so that a contributor can pick this up more easily.

Updated

**Comment by Chadha93** [comment]
@Deepansharora27 I have added a link of docs having all the information related to this issue, do take reference : )

**Comment by Deepansharora27** [comment]
Sure @Chadha93 I'll look into it
