### ISSUE TITLE
[Website] Add Tom Kerkhove to Technical Reviewers section

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-patterns/service-mesh-patterns#89]
#### Current Behavior
Tom Kerkhove is a technical review of the service mesh patterns book.

#### Details
KEDA & Promitor Maintainer, GitHub Star, Software Engineer @ Microsoft
https://github.com/tomkerkhove
https://twitter.com/tomkerkhove

**Comment by leecalcote** [comment]
@UtkarshMishra12 @Deepansharora27 @eeshaanSA @Rohith-Raju would any of you like to take this one?

**Comment by leecalcote** [comment]
@GaganpreetKaurKalsi

**Comment by eeshaanSA** [comment]
Me, I would like to take this up.

**Comment by tomkerkhove** [comment]
Ha, thanks for adding me!
