### ISSUE TITLE
No padding in the (Community Discussion Forum) button on the chapter's page (In Mobile devices)

### ISSUE THREAD

**Issue by UtkarshMishra12** [service-mesh-patterns/service-mesh-patterns#91]
#### Description

No padding in the Community Discussion Forum on the chapter's page (In Mobile devices)

#### Expected Behavior

Before
![Before](https://user-images.githubusercontent.com/67385503/201469232-373b7a46-ef99-484d-8f71-160ba80c20f8.jpg)
After
![After](https://user-images.githubusercontent.com/67385503/201469235-65fe924f-fc59-4223-96b7-e1cd69308314.jpg)

#### Environment:
- Meshery Version: 
- Kubernetes Version: 
- Host OS:
- Browser:

**Comment by UtkarshMishra12** [comment]
I would like to work on this issue.

**Comment by leecalcote** [comment]
Thank you, @UtkarshMishra12. Good eye!
