### ISSUE TITLE
[Docs] Support dark mode with light version of Service Mesh Patterns logo

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-patterns/service-mesh-patterns#94]
**Current State:**
This repo's readme doesn't consider for dark vs light mode.

**Desired State:**
Similar to other repos' readmes, include dark mode and light mode logos.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by sudhanshutech** [comment]
#95 and this are the same issues?
