### ISSUE TITLE
[Docs] Support dark mode with light version of Service Mesh Patterns logo

### ISSUE THREAD

**Issue by leecalcote** [service-mesh-patterns/service-mesh-patterns#95]
**Current State:**
This repo's [readme](https://github.com/service-mesh-patterns/service-mesh-patterns#readme) doesn't consider for dark vs light mode.

**Desired State:**
Similar to other repos' readmes, include dark mode and light mode logos.

Find logos in the brand kits here: https://layer5.io/brand.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@rajpatel17-bot, you can't find the page that is linked above? See the dark-colored "Patterns" logo?

**Comment by somaniraghav** [comment]
Can i work on this issue @leecalcote ?

**Comment by sudhanshutech** [comment]
@eeshaanSA can i work in tis issue if no one is?

**Comment by eeshaanSA** [comment]
Sure, go ahead.

**Comment by sudhanshutech** [comment]
we are talking about this logo, in the readme right?
![image](https://user-images.githubusercontent.com/90546692/219935292-201c940f-8465-46a1-b6d9-8c754801a72b.png)

**Comment by eeshaanSA** [comment]
Yes.

**Comment by sudhanshutech** [comment]
> Yes.

I have made the necessary changes, have a look
