### ISSUE TITLE
Responsiveness in small screen

### ISSUE THREAD

**Issue by sudhanshutech** [service-mesh-patterns/service-mesh-patterns#96]
#### Description

On the small screen, there is a problem with responsiveness. It is not covering the full width.

#### Expected Behavior

It should cover the whole width, the heading should be aligned center and the font size should be slightly smaller

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/90546692/219040815-fd0ed4a8-e5bd-4025-af00-ece648c403a7.png)

#### Environment:
- Meshery Version: 
- Kubernetes Version: 
- Host OS:
- Browser:

**Comment by eeshaanSA** [comment]
@sudhanshutech would you like to fix?

**Comment by sudhanshutech** [comment]
> @sudhanshutech would you like to fix?

yes sure

**Comment by Anishsme** [comment]
Can I work on this issue if no one else is ?

**Comment by Srinja333** [comment]
Can I work on this?

**Comment by ciradu2204** [comment]
can i work on this?

**Comment by nakulbh** [comment]
@leecalcote I want to work on it. Can you please assign it to me
